### ISSUE TITLE
Big smart contract deployment issue

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-json-rpc-relay#1661] opened 2023-08-22 06:56 UTC
### Description

Currently, I have received issue reports from several people who attempted to deploy complex/big smart contracts. The deployment fails randomly. I also experienced the issue myself when trying to deploy a sizable smart contract from this repository: https://github.com/hashgraph/hedera-fxprocessor-demo. 

Here is the JSON RPC log. 
https://hashdemo.com/rpc-log.txt

For my case, the contract was successfully deployed but the script returns error. I am suspecting it's because there is some delay when JSON RPC relay fetching data from the mirror node but I might be wrong.

### Steps to reproduce

1. Clone https://github.com/hashgraph/hedera-fxprocessor-demo
2. Go `web` folder
3. Install dependency
4. Configure .env
5. run `truffle migrate`

### Hedera network

mainnet, testnet

### Version

latest

### Operating system

None

**Comment by stefan-stefanooov** [comment] 2023-12-05 09:40
Hey ! @pathornteng 
I am not sure if its me but I can't open your repo:
https://github.com/hashgraph/hedera-fxprocessor-demo

Can you have a look if everything is in order ?

**Comment by pathornteng** [comment] 2023-12-05 09:42
Hi @stefan-stefanooov, thank you for taking a look. it's a private repo so I just granted you the access. Let me know if it works for you.

**Comment by stefan-stefanooov** [comment] 2023-12-05 14:15
Hello again ! 
Thank you for giving me access to the repo. 
I tried to deploy the contracts (FactoryContract) that are in the repo ....two ways.

1. Against a local node with hardhat setup. Everything went smoothly. `OK`
2. With your repo against `testnet` and as you said I get an error from truffle: 
I executed the steps that you have provided, and I get this: 
<img width="1012" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/10372129/f8e352bd-6524-46e0-8f6b-0eb1c9a9f1c9">
(Is that the error that you are getting)
...BUT the contract has been deployed I can see it in: [hashscan](https://hashscan.io) Maybe it's something in the truffle setup. `OK`

Can you give me an example of a contract the is not being deployed ? 
So that I can test this against the localnode and testnet.
As this is the main topic here, right ?

**Comment by pathornteng** [comment] 2023-12-05 17:56
Hi @stefan-stefanooov, yes, when I say it failed, I mean Truffle returns error but sometimes the smart contract got deployed successfully. The main problem is Truffle keeps returning error and the users will always assume that the transaction fails even though it's successful in some cases.

**Comment by AlfredoG87** [comment] 2023-12-05 19:09
Hello, in my experience this issue has to do with `timeout` since the deployment of large contracts involve several transactions, due to a Hedera Limitation on Max size per transaction, the contract gets divided and appended to the Hedera File Service, and once its completely uploaded, it gets deployed. so since this these are very large contracts, it takes longer to create all those transactions (under the hood by the relay) and then deploy the transaction.

HashIO has a `timeout` of `30s` however, tools (truffle) can often have their own timeouts, so is possible that you still will get a `timeout` if doing it against hashIO, but the contract gets created. but if your tool time out is less than 30 secs, it might be even more frequent. (when deploying against a mirror node, there should not be a timeout)

**Comment by pathornteng** [comment] 2023-12-05 19:20
@AlfredoG87, thank you very much for the explanation. Can we try increasing timeout of HashIO? Maybe to `60s`. I have tried increasing timeout from `Truffle` but it does not seem to fix the problem. I think this is quite crucial for the users as they will not know that the smart contract is deployed successfully if their tools return error.

**Comment by AlfredoG87** [comment] 2023-12-05 20:49
@pathornteng, I was taking a look at it seems that **HashIO** already has `60s` timeout in both `previewnet` and `testnet`, the only environment with `30s` seems to be `mainnet`.

I am open to increasing the timeout, but do we have confirmation that is indeed the issue? and what environment would that be? I ask, because we have metrics that show the latency of the request to the Relay on HashIO per environment, and I was not able to see any requests taking longer than `60s` on the last 2 days.

But did found out `8` above `30s` mark.

<img width="1673" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/ea4deee4-c706-4fd4-b83a-c383fb919e9b">

(this is for `testnet`)

**Comment by pathornteng** [comment] 2023-12-06 02:47
I am not sure because the errors are sometimes different. The first time I run I got this line 
<img width="1494" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/2261017/81a8b155-2c8c-49eb-96ea-2b09e76ac8aa">
Another time I got this one
<img width="1490" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/2261017/a87cacd9-23ce-495a-b70c-81c50054689a">
Also this one
<img width="1144" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/2261017/180934fe-b2f6-4e31-81dd-0b3d36c34ff3">

**Comment by AlfredoG87** [comment] 2023-12-06 17:07
Hello @pathornteng, not sure why the different errors, but I am quite sure that the first is definitively a `timeout` from the HashIO service, also, I was able to see 3 instances of timeouts (requests that take longer than 60s to reply) for yesterday on `testnet`.

we don't have a way in place to detect how longer after the `60s` the request took. but I've increased the `timeout` for both `previewnet` and `testnet` temporarily to `90s` while we work or figure out a way to mitigate this issue and improve the latency for such large deployments scenarios.

let me know if it works with the new timeout!

<img width="1668" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/3cb3a2c4-a940-461c-b59c-bb90e96696c6">
(this is for testnet last 24hrs)

**Comment by AlfredoG87** [comment] 2024-03-19 15:18
Hi @pathornteng, I can confirm that the timeout from the relay has been increased to `60s` but you will also need to increase the timeout on your tool, in this case is `truffle` and I think it might be network config `deploymentTimeout` but please refer to their official documentation.

Let me know if we can close this issue. Thanks!!

**Comment by pathornteng** [comment] 2024-03-21 02:11
Hi @AlfredoG87, thank you so much for your help. I can confirm that once I increased the timeout, the smart contract is deployed successfully. 

We can close this issue now :)

**Closed** 2024-03-21 15:10 UTC
Labels: bug, P1
