### ISSUE TITLE
eth_getStorageAt always returns 0x0000000000000000000000000000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by BjMrq** [hashgraph/hedera-json-rpc-relay#495] opened 2022-09-06 13:46 UTC
### Description

[eth_getStorageAt](https://ethereum.org/en/developers/docs/apis/json-rpc/?#eth_getstorageat) Does not seem to be supported and always return 0x0000000000000000000000000000000000000000000000000000000000000000

Use case: 
- detecting implementation address for upgradable contracts https://eips.ethereum.org/EIPS/eip-1967

### Steps to reproduce

- deploy a contract with a value at a specific storage location
- use eth_getStorageAt to try and get that storage

### Hedera network

testnet

### Version

testnet

**Comment by Nana-EC** [comment] 2022-09-08 22:26
HI @BjMrq 
Thanks, this is currently by design as the `eth_getStorageAt` endpoint was added in advance of necessary consensus and mirror node work to provide the needed details.
This was noted in the [v0.6.0 Release Notes](https://github.com/hashgraph/hedera-json-rpc-relay/releases/tag/v0.6.0)
We expect traceability information that would provide the correct value will start to flow through the network in 0.30.0.

Please refer to the [Hedera Status Page](https://status.hedera.com/) for info on when v0.30.0 will hit your desired environment.

**Comment by Nana-EC** [comment] 2022-09-08 22:28
Closing as there's no action to take on the relay side.
Should v0.30.0 be deployed and you still get the wrong values feel free to re-open this

**Comment by Nana-EC** [comment] 2022-10-10 18:02
This feature was pushed to 0.31, reopening

**Comment by Kalina-Todorova** [comment] 2022-11-09 12:07
This has already been fixed and released. Closing this issue.

**Closed by Kalina-Todorova** 2022-11-09 12:07 UTC
Labels: bug, limechain, P2
