### ISSUE TITLE
Headers Timeout Error when deploying large contracts

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-json-rpc-relay#2808] opened 2024-08-09 14:13 UTC
**Problem:**
The Axelar team is encountering a consistent HeadersTimeoutError when deploying large contracts. This issue occurs across various RPC providers, including QuickNode, ValidationCloud, the public RPC and when using their own relay.

**Details:**
Despite the timeout error, the contract still deploys successfully.
Example of deployed contract: [contract deploy success](https://hashscan.io/testnet/contract/0.0.4643580)
Example bytecode: [AxelarGateawayData.txt](https://github.com/user-attachments/files/16562185/AxelarGateawayData.txt)

**Impact:**
This issue affects the deployment process by causing unnecessary errors, which could mislead developers into thinking the deployment failed when it really succeeded. Resolving this issue would also allow Axelar to not need custom configs for their rpc which would be more in parity with other evms they have integrated.

**Comment by quiet-node** [comment] 2024-08-14 17:56
I have tried reproducing this issue on the local Relay pointing to testnet, as well as on the HashIO relay, using the same bytecode from `AxelarGateWayData.txt`. However, I was unable to reproduce the timeout issue on either instance.

![Screenshot 2024-08-14 at 12:24:50 PM](https://github.com/user-attachments/assets/f3511cbb-6c37-4238-9e46-b001afcff11c)

As shown in the screenshot above, it takes around 25 seconds to complete the deployment job, and no timeout error was thrown. Here is an example of the deployed contract: [https://hashscan.io/testnet/transaction/1723656880.276860003](https://hashscan.io/testnet/transaction/1723656880.276860003).

Is it possible for you to show what the log says when a timeout error is thrown? Additionally, a list of the Relay's configuration settings would be helpful to review as well.

**Comment by natanasow** [comment] 2024-08-20 09:46
Hi @mgarbs, I might know what's happening if you're using hardhat. When we create a contract deployment, the relay under the hood executes 1x`FileCreate` + N*`FileAppend`s which takes some time. After the file (with the contract's content) has been created, the relay passes the main signed Ethereum contract deploy transaction to the services for further execution. If we're waiting for the receipt to be populated in the mirror node, the entire process might take up to 30 seconds against testnet for the bytecode you have posted above.

By default, hardhat-ethers set the `HeadersTimeoutError` to 20 seconds, so if we exceed these seconds, the error is thrown but the request has been already sent for execution and that's why the contract is deployed but the end-user receives an error for timeout.

The flow might be described as follows:
- hardhat user sends `eth_sendRawTransaction` for contract deployment and starts waiting for its receipt - the timeout timer is started here and has 20 seconds to receive the receipt
- our relay handles that request and creates 1x`FileCreate` and N*`FileAppend`s txs - this step can take a while (more than 20 seconds)
- hardhat user is waiting for the receipt but the timeframe of 20 seconds is reached and a timeout error is thrown
- the relay finally executes all of the transactions and receives the receipt from the mirror node but it's already too late because

:point_up: **results in successful contract deployment but in timeout error for the hardhat user.**

---

<p align="center"><img src="https://i.ibb.co/DWQSK7t/u2-Po4-Ou6-Mr-Nr-A1-VBZqq0.png"/></p>

---

Here is an example of my `hardhat.config.js`.
```typescript
  ...
  defaultNetwork: 'testnet',
  networks: {
    testnet: {
      timeout: 50_000, // ran some tests with different values and > 30 secs is enough for your contract
      url: 'https://testnet.hashio.io/',
      accounts: [
          '0x...'
      ],
      chainId: 296,
      ...
  }
  ...
```

The core problem is not related to RPC relays and it lies in the hardhat-ethers default timeout which can be overridden easily IMO. Hope that's useful for you and also kinda resolves your issue. Feel free to share all of your concerns.

**Comment by Neurone** [comment] 2024-08-27 00:01
I faced the same issue when deplying [EAS](https://github.com/ethereum-attestation-service/eas-contracts), and using `timeout: 50_000` in hardhat configuration solved the issue!

**Comment by ebadiere** [comment] 2024-08-27 17:56
@mgarbs I believe @natanasow 's explanation and solution should resolve this issue.  I am closing it for now.  Please feel free to open it or create a new issue if it does not resolve the problem.

**Closed by ebadiere** 2024-08-27 17:56 UTC
Labels: bug

**Comment by mgarbs** [comment] 2024-08-28 14:32
Thanks @ebadiere
