### ISSUE TITLE
Error invoking RPC: Cannot read properties of null (reading 'balance') with Foundry

### ISSUE THREAD

**Issue by tinypell3ts** [hashgraph/hedera-json-rpc-relay#1674] opened 2023-08-23 09:35 UTC
### Description

I'm trying to deploy a contract using [Foundry](https://book.getfoundry.sh/) on Testnet using the JSON RPC Relay. It's throwing an error when fetching the balance. It looks like the address it's trying to get the balance for is `0x5b73c5498c1e3b4dba84de0f1833c4a029d90519`, whereas my Testnet EVM address is `0x471fa89ecd40f5bd326da89950c20d6365400a58`. I can successfully deploy the same contracts on multiple other EVM networks.

### Steps to reproduce

1. Run `forge init hello_foundry`
2. Create `.env` and add Testnet HEX Encoded Private Key (ECDSA) as `PRIVATE_KEY`
3. Update `Counter.s.sol`

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Script.sol";
import {Counter} from "../src/Counter.sol";

contract Deploy is Script {
    function run() public {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);

        Counter counter = new Counter();

        vm.stopBroadcast();
    }
}
```

4. Add RPC url to `foundry.toml`
```toml
[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
hedera-testnet = "https://testnet.hashio.io/api"
```

5. Run `forge script script/Counter.s.sol:Deploy --rpc-url hedera-testnet --broadcast -vvvv`

### Additional context

```bash
➜  hello_foundry git:(main) ✗ make deploy-Counter
forge script script/Counter.s.sol:Deploy --rpc-url hedera-testnet --broadcast -vvvv
[⠔] Compiling...
No files changed, compilation skipped
2023-08-23T09:20:21.464951Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x5b73c5498c1e3b4dba84de0f1833c4a029d90519, 
(code: -32603, message: [Request ID: a37bfe75-998c-439c-baef-ac6d2951a825] Error invoking RPC: Cannot read properties of null (reading 'balance'), data: None)) address=0x5b73c5498c1e3b4dba84de0f1833c4a029d90519
2023-08-23T09:20:24.649122Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x5b73c5498c1e3b4dba84de0f1833c4a029d90519, 
(code: -32603, message: [Request ID: 34697036-5357-4729-8f00-da060b2d047a] Error invoking RPC: Cannot read properties of null (reading 'balance'), data: None)) address=0x5b73c5498c1e3b4dba84de0f1833c4a029d90519
2023-08-23T09:20:28.039170Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x0000000000000000000000000000000000000000, 
(code: -32603, message: [Request ID: 2572108e-40bd-4823-96f1-3a926c71b468] Error invoking RPC: Cannot read properties of null (reading 'balance'), data: None)) address=0x0000000000000000000000000000000000000000
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /Users/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/revm-2.3.1/src/evm_impl.rs:285
```

### Hedera network

testnet

### Version

v0.29.1

### Operating system

macOS

**Comment by AlfredoG87** [comment] 2023-08-23 15:17
Hi @tinypell3ts , thank you for reporting the bug, we are aware of a bug when on `eth_getBalance` that returns `500` status with the provided message `Cannot read properties of null (reading 'balance')`.

There are 2 tickets that have already been merged and deployed as part of the release process for version `0.30` on version `0.30.0-rc3` that has been recently deployed on `testnet` and `previewnet`.

We will wait a couple days until we create the GA version and deploy it on `mainnet` but as of today the issue should be fixed on both `previewnet` and `testnet`

**Tickets for reference:**
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1648
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1670


Please could you try again and confirm if the issue is indeed solved for you too?

**Comment by AlfredoG87** [comment] 2023-08-23 16:46
Am glad to hear most of your issues were resolved, specially with the `eth_getBalance`  `Cannot read properties of null` errors.

With respect to other issue `INVALID_SOLIDITY_ADDRESS`. I am not sure of why is it happening, so yeah, go ahead and open another ticket for that, please include all the relevant details and how to reproduce it. even a project files or link to github are really useful for evaluating that type of issues. 👍  

Thank you for reporting! 💯 

PS: am closing this ticket as the main issue is resolved.

**Closed by AlfredoG87** 2023-08-23 16:46 UTC
Labels: bug
