### ISSUE TITLE
Metamask versions 10.30.1 and 10.30.2 are unable to connect to Hedera JSON RPC

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-json-rpc-relay#1250] opened 2023-05-15 22:31 UTC
### Description

The new version of the metamask browser extension no longer connects to Hedera JSON RPC relay endpoints.
It gets stuck trying to connect and gies up.
This blocks the use of the wallet and therefore ability to submit transaction and check on wallet balances and interact with DApps

### Steps to reproduce

1. Update metamask browser extension above 10.29.0
2. Try to connect to any hosts JSON rpc
3. Observe the "Connection to ..." messag
4. Observe "Oops! Something went wrong."

![Screenshot 2023-05-15 at 3 46 03 PM](https://github.com/hashgraph/hedera-json-rpc-relay/assets/56320167/e80452c1-3f2f-4165-9fcb-bb092d79a6ff)

### Additional context

[10.29.0](https://github.com/MetaMask/metamask-extension/releases/tag/v10.29.0) seems to be the last working version.

### Hedera network

mainnet

### Version

v0.23.0

### Operating system

None

**Comment by AlfredoG87** [comment] 2023-05-15 22:52
Found  that  the  new version of  metamask  does  a  request  to 
GET   https://gas-api.metaswap.codefi.network/networks/296/suggestedGasFees

and gets  a 500 error.

<img width="1692" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/87df3b67-1464-4916-950f-6078da0f638f">
<img width="1265" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/508207b3-a0a1-4fd7-9b4c-406f307d8324">

The  error on the body of  the request  is:
<img width="682" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/acc6eec4-ec98-48d9-a786-882ec954a6cd">


However  that  happens also with any non-existent  chainId that  I try with:

I compared the console  of the `10.29.0`  version  of metamask,  wherre Hedera network is working and it does not perform that request, neither shows errors:

<img width="1715" alt="image" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/123040664/0632a564-4995-417b-9822-c698a09d3b04">

**Comment by AlfredoG87** [comment] 2023-05-15 23:26
Closed this ticket since I've  found that  Metamask  just released a new version 10.30.3 that  corrects  this error,  looks like they had a  regression  and just released a patch to restore support for other chains.
https://github.com/MetaMask/metamask-extension/releases/tag/v10.30.3
What changed?
https://github.com/MetaMask/metamask-extension/compare/v10.30.2...v10.30.3
I already downloaded manually 10.30.3 version and installed and tested and the error is resolved :partying_face:
So we only need to wait for Chrome to pick up the update and roll it  out.

**Closed** 2023-05-15 23:25 UTC
Labels: bug, P1, wallets
