### ISSUE TITLE
`block.chainid` is returning 0 when invoked from contract

### ISSUE THREAD

**Issue by kabaluyot** [hashgraph/hedera-json-rpc-relay#1375] opened 2023-06-20 05:39 UTC
### Description

Not sure if this is related here on rpc relay or in the EVM itself but the `block.chainid` which is heavily used when implementing typed signed data (EIP712) is returning `0`.

I suspect that my typed signed data signature verification fails because of this incorrect chain Id. It is returning correct results across other EVM chains.

It was stated that the block.chainid opcode is supported according to https://docs.hedera.com/hedera/core-concepts/smart-contracts/solidity-variables-and-opcodes

<img width="873" alt="Screen Shot 2023-06-20 at 1 33 53 PM" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/e1876a5a-a3a5-4af7-aee1-04b8e42e23c3">

Here is the view function to return the block.chainid:

Contract.sol
```
    function getContractAddress() external view returns (address) {
        return address(this);
    }

    function getChainId() external view returns (uint256) {
        return block.chainid;
    }
```

hardhat.js
```
  // test: get contract address
  const res1 = await dao.getContractAddress();
  console.log("CONTRACT ADDRESS:", res1);

  // test: get chain id
  const res2 = await dao.getChainId();
  console.log("CHAIN ID:", res2);
```

Result:
<img width="397" alt="Screen Shot 2023-06-20 at 1 38 28 PM" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/c4294737-ac66-49dd-be95-65af07526972">

### Steps to reproduce

1. Try to query block.chainid from contract
2. It returns 0

It affects EIP712.sol as it is using block.chainid

### Hedera network

testnet

### Version

latest

### Operating system

None

**Comment by kabaluyot** [comment] 2023-06-20 07:13
Tried overriding block.chainid with `296` still receiving invalid signature. Is there a working example or is EIP712 itself supported in Hedera?

Tried this on other chains,  all good .. only on Hedera EVM

![image](https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/566743c7-ade2-483c-a36a-d52f442091c0)

**Comment by Nana-EC** [comment] 2023-06-22 00:25
Hey @kabaluyot.
Thanks for bringing this up, we're not able to reproduce your issue.
`block.chainid` has been seen to work and responds with the appropriate chainId value.

We'd like to get to the bottom of this especially as you noted it's working on other EVMs.
Can you provide a simple E2E flow (complete .sol contract and .js test file) that we can use to confirm your context around the chainID and 712 flow you're trying to achieve.

**Comment by Nana-EC** [comment] 2023-06-22 00:53
@kabaluyot update here. 
We seem to have reprod the `block.chainid` issue in testnet now. 
Local node does not seem to have this issue.

We're continuing to investigate to get to the bottom of this
The reference repo code with your 712 flow will still be useful for continued investigation.
Thanks

**Comment by JeromeK13** [comment] 2023-06-27 15:12
Hey All

Just tested this locally with the following configurations and it works. So seems like this error only applies to the hosted relays of Arkhia and hashio

call.js
```js
const contractJson = require('../artifacts/contracts/Lock.sol/ChainId.json');

async function main() {
  const { Web3 } = require('web3');
  var web3 = new Web3('http://localhost:7546/');
  const contract = new web3.eth.Contract(contractJson.abi, '0x0000000000000000000000000000000000e4d010');
  await contract.methods
    .getChainId()
    .call()
    .then((chainId) => console.log(`Chain ID: ${chainId}`))
    .catch((error) => console.error(`An error occurred: ${error}`));
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

contract.sol
```sol
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.9;

contract ChainId {
    function getContractAddress() external view returns (address) {
        return address(this);
    }

    function getChainId() external view returns (uint256) {
        return block.chainid;
    }
}
```

.env of the relay
```
HEDERA_NETWORK=testnet
OPERATOR_ID_MAIN=0.0.XXXX
OPERATOR_KEY_MAIN=XXX
CHAIN_ID=0x128
MIRROR_NODE_URL=https://testnet.mirrornode.hedera.com/
```

**Comment by Nana-EC** [comment] 2023-07-07 00:07
@JeromeK13 , could you you verify you're all set by pointing to previewnet.
The item was resolve on the mirror node in 0.84

**Comment by quiet-node** [comment] 2023-07-25 23:42
Hey @kabaluyot  and @JeromeK13 , I was able to set up my reproducer environment just like yours and glad to report that  that the problem has been resolved. The `block.chainid` now returns the correct expected chainIds -- `0x128` or `296` for `testnet` -- `0x129` or `297` for `previewnet`. 

For reference, you can check out the transactions on Hashscan, where I've emitted a custom event displaying the correct chainId. It should be at the end where the `logs` section is located.

testnet - https://hashscan.io/testnet/transaction/1690326936.803978041
previewnet - https://hashscan.io/previewnet/transaction/1690327950.359081003

**Comment by Nana-EC** [comment] 2023-07-25 23:45
Thanks @quiet-node 
Closing this ticket as we've confirmed fix.

**Closed by Nana-EC** 2023-07-25 23:45 UTC
Labels: bug, P1
