### ISSUE TITLE
Errors when invoking contract write calls (just happened lately)

### ISSUE THREAD

**Issue by kabaluyot** [hashgraph/hedera-json-rpc-relay#1607] opened 2023-08-07 10:29 UTC
### Description

Right now, even if I use our own hedera json relay, Arkhia, public hedera testnet, there's a high chance of failure when invoking smart contract function call. This doesn't happen before.

### Steps to reproduce

1. Call a `write` function in a deployed contract using hedera json relay
2. Errors related to "eth_blocknumber" appears

Please see attachment below.

### Additional context

![image](https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/55599584-34bb-4260-890f-4ecdec47407c)

### Hedera network

testnet

### Version

latest main, happening also in v0.29.0

### Operating system

None

**Comment by georgi-l95** [comment] 2023-08-07 14:07
Hey @kabaluyot can you give some more details as to how can i reproduce this error ? Are you using hardhat or calling the write function using metamask or something else ?
I've tried this using metamask and it seems to be working.

**Comment by kabaluyot** [comment] 2023-08-07 15:12
@georgi-l95 using MetaMask. Will give more details tomorrow and the contract

**Comment by georgi-l95** [comment] 2023-08-22 09:12
@kabaluyot do you still have this issue ?

**Comment by kabaluyot** [comment] 2023-08-22 09:14
Yes .. but I think this happens when invoked from MetaMask .. Invoking it via hardhat works

**Comment by kabaluyot** [comment] 2023-08-22 09:18
Issue is like this: https://github.com/hashgraph/hedera-json-rpc-relay/issues/1631

**Comment by georgi-l95** [comment] 2023-08-22 09:19
Oh, okay. Let's wait then for #1631 to get merged and you can check again.

**Comment by kabaluyot** [comment] 2023-08-22 09:21
Also related to this: https://github.com/hashgraph/hedera-json-rpc-relay/issues/1580

Invoking contract calls (write calls) in Metamask most likely fails. Even transferring HBARS from wallet to wallet in metamask

**Comment by kabaluyot** [comment] 2023-08-22 09:23
Also aside from using hedera testnet rpc, arkhia rpc, and THA rpc, we spinoff our own rpc to check the issue (latest master).

Own RPC node: parseTransaction errors in logs and eth_sendRawTransactions errors in logs when invoking write transactions.

So we have created our own node too:
http://34.242.86.166:7546/
With latest master build (commit hash: a3dd16e3023faab5e5bade106bfc808241efd775)
.env
```
# mandatory env variables to run the relay successfully. See README.md for more details and ./docs/examples for HashIO previewnet, testnet and mainnet templates
CHAIN_ID=0x128
MIRROR_NODE_URL=https://testnet.mirrornode.hedera.com/
HEDERA_NETWORK=testnet
#mandatory env variables to support queries and transactions to Consensus Node e.g. eth_sendRaTransaction and fallback scenarios on calls to Mirror Node
OPERATOR_ID_MAIN=0.0.452467
OPERATOR_KEY_MAIN=<key-main>
```

![image](https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/2f5d72ad-2b1d-4eed-a036-cad892637ca7)

![image](https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/41adfe24-f90f-47a8-804e-2f6caf0eaefb)

**Comment by georgi-l95** [comment] 2023-08-22 10:14
Okay, thanks for the input. We'll look into it.

**Comment by natanasow** [comment] 2023-08-23 08:29
@kabaluyot Could you try to run `npm install && npm run build` again. Recently, we updated the ethers version from v5 to v6. In ethers v6 the  `ethers.utils.parseTransaction(<rlpHash>)` method was completely removed, and transaction decoding is done via  `Transaction.from(<rlpHash>)`. 

IMO, you successfully pulled the latest version of relay (or commit sha) with the updated version of ethers but you did not update dependencies and rebuild the relay. If you open `precheck.ts` you might see `parseTransactionIfNeeded` is using `Transaction.from` while your error shows that the target method is `ethers.utils.parseTransaction`, and that's because your relay is using an old build.

**Comment by kabaluyot** [comment] 2023-08-23 11:21
Looks like the issue with parseTransaction is now fixed. Can confirm by pulling latest build

Only issue I get now is metamask related, like sending hbars/erc20 tokens in metamask, it throws this:

<img width="1680" alt="Screen Shot 2023-08-23 at 7 21 21 PM" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/36bfaaee-a732-4ab6-8375-83b9ceb91a5d">

**Comment by natanasow** [comment] 2023-08-24 08:03
@kabaluyot Reset (incl. nonce) your metamask account and try again. [Here](https://support.metamask.io/hc/en-us/articles/360015488891-How-to-clear-your-account-activity-reset-account) is described how could be done.

**Comment by kabaluyot** [comment] 2023-08-24 09:03
@natanasow can now send funds via metamask when reseting nonce. Thanks for the guide

**Comment by kabaluyot** [comment] 2023-08-24 09:59
but .. the nonce issue is frequently appearing .. after some time resetting in metamask, after some success tx (now interacting with a smart contract), sometimes it gets that nonce error then all succeeding call fails .. but it can be easily resolved by resetting again the nonce in metamask

**Comment by natanasow** [comment] 2023-08-25 05:50
If you reset the nonce in metamask and transaction execution is successful afterward, I don't think there is an issue in the relay. I might suggest waiting for the transaction receipt or at least waiting a little bit longer between contract interactions, thus the nonce will be always accurate in metamask and there will be no race conditions in relays (e.g. executing a signed tx with nonce X after tx with nonce X+1 which causes your issues IMO).

**Comment by Nana-EC** [comment] 2023-09-21 05:12
@kabaluyot looks like the few issues not in here were resolved.
Please let us know if not and we can reopen this.

**Closed by Nana-EC** 2023-09-21 05:12 UTC
Labels: bug, limechain
