### ISSUE TITLE
Do not set admin key on contract create for parity with EVM chains

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#585] opened 2022-10-04 11:52 UTC
### Problem

The relay's current behaviour appears to default the `adminKey` to the contract deployer on creating a contract(I couldn't find where the `adminKey` was set to the deployer on contract create). This means the contract deployer has privileges that they do not have on standard  EVM chains which do not have contract admins. For example, the deployer can transfer HTS funds from a contract.

### Solution

- For parity with Ethereum the `adminKey` should be not set as the default access control on contracts should correspond with Ethereum which does not have contract admins.
- To allow for the `adminKey` to be set extend the `eth_sendRawTransaction ` method(i.e. the method used to create contracts) with an optional `adminKey` field.

**Comment by Nana-EC** [comment] 2022-10-04 14:11
Hi @mshakeg can you provide more details on a run in testnet.
Preferably the dev tool being used and the call, a contract example, and the eventual contract id to help us get a better sense of the context.
Thanks

**Comment by mshakeg** [comment] 2022-10-04 17:45
@Nana-EC yeah, I was also doubtful it was at the relay level as stated in the original message:
> I couldn't find where the adminKey was set to the deployer on contract create

And as far as I'm aware it isn't at the SDK level either as the `adminKey` has to be explicitly set using `setAdminKey`.

If you look inside `./test/malory/MalRouter.test.ts` you'll see that the default `hre.ethers` signer(for relay calls including contract create and contract calls) i.e. `(await hre.ethers.getSigners())[0]` appears to be granted admin privileges as they can transfer HTS tokens owned by a contract(they deployed) provided that contract was called in a given evm execution.

I haven't tested deploying a contract using only the SDK(i.e. not going through the relay) would grant admin privileges to the deploying account, but if it did then the issue is definitely not with the relay and I'd imagine the issue would either be at the core network layer and if not then it's probably the SDK defaulting the `adminKey` to the client publicKey.

I've also engaged with mark_williamson on this issue.

**Comment by georgi-l95** [comment] 2022-10-12 14:49
Admin key is being set in the [hedera-services](https://github.com/hashgraph/hedera-services) , not in the relay or SDK. It's set to be the same as the sender for all contracts created with ethereum transactions. This [function](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/SynthCreationCustomizer.java#L48) is used to set the admin key. 
By design it inherits the properties from the payer.

**Comment by mshakeg** [comment] 2022-10-12 16:57
@georgi-l95 thanks for confirming that, seems like a deliberate decision, why is that? Wouldn't it make more sense to not set the payer as the admin by default for parity with Ethereum?

**Comment by Nana-EC** [comment] 2022-10-12 19:55
Yeah @mshakeg it's by design.
At this stage it's a feature discussion as indeed not setting the key would be more Ethereum like.
We'll continue investigation and circle back on this.

Notably I'll close this ticket with findings and the path forward once we're concluded.
Per the investigation any changes would be on the network service repo and not here.

**Comment by Nana-EC** [comment] 2022-10-18 23:34
@mshakeg closing this as I opened https://github.com/hashgraph/hedera-services/issues/4097 since work would be done on services to address this.

Thanks again for this
Feel free to share any other suggestions as push for EVM equivalence for the HSCS :)

**Closed by Nana-EC** 2022-10-18 23:34 UTC
Labels: enhancement, limechain, P1
