### ISSUE TITLE
No matching record rpc error when invoked from metamask

### ISSUE THREAD

**Issue by kabaluyot** [hashgraph/hedera-json-rpc-relay#1708] opened 2023-09-03 13:12 UTC
### Description

This error is a bit tricky, it happens when calling functions from metamask and sometimes it works, sometimes it doesnt. By playing around with gas limits, looks like sometimes it needs a hardcoded gas limit vs the one suggested by metamask.

Would be trivial if the error returned by rpc says 'insufficient gas' instead of the shown error.

### Steps to reproduce

1. Try to send hbar, erc20 tokens via metamask from wallet to wallet
2. In a high certainty, you can get this error failing the transfer transaction
3. It can also be triggered by invoking smart contact write functions

### Additional context

from metamask logs
![image](https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/3d439b6b-f656-4b6e-a5df-78b8ac7ba19a)

from client side logs
<img width="1519" alt="Screen Shot 2023-09-03 at 9 11 17 PM" src="https://github.com/hashgraph/hedera-json-rpc-relay/assets/38805756/9e1bb1e8-1969-4c30-b6ad-97d97f1fa1f9">

### Hedera network

testnet

### Version

latest master (cf48856a9957712d7cdced47e6812663aeaf94d7)

### Operating system

None

**Comment by ebadiere** [comment] 2023-09-21 19:31
@ kabaluyot Are you still seeing this?  If so do you have a contract on testnet that can be used to reproduce it?  I tried several transfers, as well as invoking update functions in contracts and I didn't see this.

**Comment by ebadiere** [comment] 2023-10-06 21:03
@kabaluyot Closing this as I cannot reproduce it.  Feel free to open it again if you see it reoccur.

**Closed by ebadiere** 2023-10-06 21:03 UTC
Labels: bug
