### ISSUE TITLE
subgraph-example project startblock failed dependency

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-json-rpc-relay#591] opened 2022-10-05 10:24 UTC
### Description

The graph node in the `subgraph-example` project attempts to `eth_getBlockByNumber` from block 0(presumably genesis if zero-indexed on Hedera), however should instead attempt to get blocks from the `startBlock`(as stated in the [README](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/tools/subgraph-example/README.md#deploy-the-subgraph-to-the-local-graph-node)) as specified in the `subgraph.yaml` set to `X`(i.e. X >= blockNumber when Greeter was deployed).

```yaml
    source:
      address: "0x0000000000000000000000000000000000000408"
      abi: Greeter
      startBlock: 700
```

`graph-node_1` logs:
```
graph-node_1  | Oct 05 09:55:50.949 INFO Graph Node version: 0.27.0 (2022-08-01)
graph-node_1  | Oct 05 09:55:50.966 WARN GRAPH_POI_ACCESS_TOKEN not set; might leak POIs to the public via GraphQL
graph-node_1  | Oct 05 09:55:50.966 INFO Generating configuration from command line arguments
graph-node_1  | Oct 05 09:55:50.966 WARN No fork base URL specified, subgraph forking is disabled
graph-node_1  | Oct 05 09:55:50.966 INFO Starting up
graph-node_1  | Oct 05 09:55:50.966 INFO Trying IPFS node at: http://ipfs:5001/
graph-node_1  | Oct 05 09:55:51.125 INFO Creating transport, capabilities: archive, traces, url: http://host.docker.internal:7546, provider: local-rpc-0
graph-node_1  | Oct 05 09:55:51.188 INFO Successfully connected to IPFS node at: http://ipfs:5001/
graph-node_1  | Oct 05 09:55:51.436 INFO Connecting to Postgres, weight: 1, conn_pool_size: 10, url: postgresql://graph-node:HIDDEN_PASSWORD@postgres:5432/graph-node?sslmode=prefer, pool: main, shard: primary
graph-node_1  | Oct 05 09:55:51.466 INFO Pool successfully connected to Postgres, pool: main, shard: primary, component: Store
graph-node_1  | Oct 05 09:55:51.599 INFO Setting up fdw, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Oct 05 09:55:51.619 INFO Running migrations, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Oct 05 09:55:51.631 INFO Migrations finished, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Oct 05 09:55:51.632 INFO Mapping primary, pool: main, shard: primary, component: ConnectionPool
graph-node_1  | Oct 05 09:55:51.814 INFO Connecting to Ethereum to get network identifier, capabilities: archive, traces, provider: local-rpc-0

graph-node_1  | Oct 05 09:55:52.296 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #10) with result Err(Ethereum node could not find genesis block), provider: local-rpc-0
graph-node_1  | Oct 05 09:55:52.910 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #11) with result Err(Ethereum node could not find genesis block), provider: local-rpc-0
graph-node_1  | Oct 05 09:55:54.736 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #12) with result Err(Ethereum node could not find genesis block), provider: local-rpc-0
graph-node_1  | Oct 05 09:55:56.126 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #13) with result Err(Ethereum node could not find genesis block), provider: local-rpc-0
graph-node_1  | Oct 05 09:56:00.506 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #14) with result Err(Ethereum node could not find genesis block), provider: local-rpc-0
graph-node_1  | Oct 05 09:56:02.509 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #15) with result Err(Ethereum node could not find genesis block), provider: local-rpc-0
graph-node_1  | Oct 05 09:56:21.557 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #16) with result Err(Ethereum node could not find genesis block), provider: local-rpc-0
graph-node_1  | Oct 05 09:56:21.811 ERRO Connection to provider failed. Not using this provider, error: deadline has elapsed, provider: local-rpc-0

graph-node_1  | Oct 05 09:56:21.835 ERRO No store configured for Ethereum chain local; ignoring this chain
graph-node_1  | Oct 05 09:56:21.893 INFO Creating LoadManager in disabled mode, component: LoadManager
graph-node_1  | Oct 05 09:56:21.897 INFO Starting firehose block ingestors with 0 chains []
graph-node_1  | Oct 05 09:56:21.897 INFO Starting firehose block ingestors with 0 chains []
graph-node_1  | Oct 05 09:56:21.897 INFO Starting firehose block ingestors with 0 chains []
graph-node_1  | Oct 05 09:56:21.903 INFO Starting job runner with 4 jobs, component: JobRunner
graph-node_1  | Oct 05 09:56:21.909 INFO Starting JSON-RPC admin server at: http://localhost:8020, component: JsonRpcServer
graph-node_1  | Oct 05 09:56:21.924 INFO Starting GraphQL HTTP server at: http://localhost:8000, component: GraphQLServer
graph-node_1  | Oct 05 09:56:21.930 INFO Started all assigned subgraphs, node_id: default, count: 0, component: SubgraphRegistrar
graph-node_1  | Oct 05 09:56:21.932 INFO Starting index node server at: http://localhost:8030, component: IndexNodeServer
graph-node_1  | Oct 05 09:56:21.935 INFO Starting metrics server at: http://localhost:8040, component: MetricsServer
graph-node_1  | Oct 05 09:56:21.936 INFO Starting GraphQL WebSocket server at: ws://localhost:8001, component: SubscriptionServer
```

### Steps to reproduce

1. Run `hardhat-example` project rpc test which should deploy the `Greeter` contract.
2. Set the `startBlock` and the `Greeter` contract address in `subgraph.yaml` accordingly
3. Deploy the local graph node by running `yarn graph-local` in the `subgraph-example` project root
4. After postgres(green logs) and ipfs(yellow logs) start up the graph-node logs(blue) should be visible and observe that the graph-node attempts and fails to get `eth_getBlockByNumber(0, false)` when it should instead attempt to get `eth_getBlockByNumber(X, false)` where `X` is the `startBlock`

### Hedera network

other

### Version

local-node@1.2.0

### Operating system

macOS

**Comment by dimitrovmaksim** [comment] 2022-10-05 13:33
`yarn graph-local` only spins up the local `graph-node`, then it starts syncing the blocks. 

The configurations in the `subgraph.yaml` will only work after deploying the subgraph itself https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/tools/subgraph-example/README.md#deploy-the-subgraph-to-the-local-graph-node
`startBlock` tells the deployed subgraph to start looking for triggers, in this case events, from this block onwards. 

So the graph-node behaviour is correct. The issue is the lack of a genesis block (I'm assuming this is run against the local node)

There is another property that can be set in the graph-node docker-compose.yaml `GRAPH_ETHEREUM_GENESIS_BLOCK_NUMBER` that changes the graph-node genesis block number https://github.com/graphprotocol/graph-node/blob/master/docs/environment-variables.md

**Comment by dimitrovmaksim** [comment] 2022-10-05 16:53
No problem. I'll have to update the docker-compose.yaml and the readme.

**Comment by mshakeg** [comment] 2022-10-06 17:38
I've confirmed that everything else works as expected

**Comment by Kalina-Todorova** [comment] 2022-10-12 07:34
Great to hear, closing the issue.

**Closed by Kalina-Todorova** 2022-10-12 07:34 UTC
Labels: bug, limechain, P3
